# Generated by Django 3.0.8 on 2020-07-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200702_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='types',
            field=models.ManyToManyField(related_name='businesses', to='main.BusinessType'),
        ),
    ]
