# Generated by Django 3.0.8 on 2020-07-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_business_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='web_site',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='business',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
