# Generated by Django 3.0.8 on 2020-07-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200702_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='web_site',
            new_name='website',
        ),
    ]
