# Generated by Django 3.0.8 on 2020-07-14 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200702_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
