# Generated by Django 3.0.8 on 2020-07-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_business_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='rating',
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.CharField(max_length=250),
        ),
    ]
